apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hsds-viewer.fullname" . }}
  labels:
    {{- include "hsds-viewer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hsds-viewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "hsds-viewer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.ingress.enabled }}
            - name: USE_PROXY_FIX
              value: "True"
            {{- end }}
            - name: HS_ENDPOINT
              value: {{ .Values.hsds.endpoint }}
            {{- if .Values.hsds.defaultUser }}
            - name: HSDS_DEFAULT_USER
              value: {{ .Values.hsds.defaultUser }}
            {{- end }}
            {{- if .Values.hsds.defaultRoles }}
            - name: HSDS_DEFAULT_ROLES
              value: {{ .Values.hsds.defaultRoles | join "," }}
            {{- end }}
            {{- if .Values.hsds.credentials }}
            - name: HSDS_CREDENTIALS_FILE
              value: /credentials.json
            {{- end }}
            {{- if .Values.features.nodeInfo }}
            - name: FEATURE_NODE_INFO_ENABLED
              value: "1"
            {{- end }}
            {{- if .Values.features.monitoringDashboard }}
            - name: FEATURE_MONITORING_DASHBOARD_ENABLED
              value: "1"
            {{- end }}
            {{- if .Values.oidc.enabled }}
            - name: OIDC_ENDPOINT
              value: {{ .Values.oidc.endpoint }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidc.client }}
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-oidc
                  key: secret
            - name: OIDC_ROLES_CLAIM
              value: {{ .Values.oidc.rolesClaim }}
            {{- end }}
          {{- if .Values.hsds.credentials }}
          volumeMounts:
            - name: credentials
              subPath: credentials.json
              mountPath: /credentials.json
              readOnly: true
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.hsds.credentials }}
      volumes:
        - name: credentials
          secret:
            secretName: {{ .Release.Name }}-credentials
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
