{{- if .Values.oidc.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oidc
  labels:
    {{- include "hsds-viewer.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.oidc.secret | b64enc | quote }}
{{- end -}}
