{{- if .Values.hsds.credentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  labels:
    {{- include "hsds-viewer.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.hsds.credentials | toJson | b64enc | quote }}
{{- end }}
