apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  labels:
    {{- include "hsds-viewer.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.hsds.username | b64enc | quote }}
  password: {{ .Values.hsds.password | b64enc | quote }}
