name: Docker Image CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: fabianmp/hsds-viewer
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=semver,pattern={{raw}}
      - name: Docker meta dev image
        id: meta-dev
        uses: docker/metadata-action@v3
        with:
          images: fabianmp/hsds-viewer
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }},suffix=-dev
            type=semver,pattern={{raw}},suffix=-dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Build and push dev image
        uses: docker/build-push-action@v2
        with:
          push: true
          target: dev
          tags: ${{ steps.meta.outputs.tags }}
